# Generated by Django 4.0.3 on 2022-03-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='username'),
        ),
    ]
